### ISSUE TITLE
회원권 등록이랑 레슨등록 구분해서 받아주길 요망함 ㅠㅜ

### ISSUE THREAD

**Issue by gwuiinKim** [d-ew/Server#1]
서버에서 course별  reducing 방식으로 구분해서 받아준 것은 상당히 인사이트있는 결정이었다고 생각하지만

지금 방식에서 횟수 reducing 방식으로 get 했을 때, 그 course가 회원권인지 레슨인지 클라이언트 측에서 구분할 방법이 없는 것 같아

아무래도 회원권이랑 레슨은 client측에선 명확히 구분해서 받아야 하기 때문에
번거롭겠지만 협조 좀 부탁!!!

**Comment by smallfish06** [comment]
Mvp모델에서는 우선적으로 지난번에 회의한거처럼 레슨은 제외하고 회원권만 개발함다!
